#include "stm32g070xx.h"

void gpio_init(void)
{
 RCC->IOPENR |= RCC_IOPENR_GPIOAEN | RCC_IOPENR_GPIOBEN;
 
 GPIOA->MODER &= ~( GPIO_MODER_MODE8_Msk | GPIO_MODER_MODE9_Msk);
 GPIOA->MODER |= (GPIO_MODER_MODE8_0 | GPIO_MODER_MODE9_0);
 
 GPIOA->MODER &= ~(GPIO_MODER_MODE5_Msk | GPIO_MODER_MODE6_Msk | GPIO_MODER_MODE7_Msk);
 GPIOA->MODER |= (GPIO_MODER_MODE5_0 | GPIO_MODER_MODE6_0 | GPIO_MODER_MODE7_0);
 
 GPIOB->MODER &= ~(GPIO_MODER_MODE5_Msk | GPIO_MODER_MODE0_Msk);
 GPIOB->MODER |= (GPIO_MODER_MODE5_0 | GPIO_MODER_MODE0_0);

} 